copy input01.txt input.txt
solution
copy output.txt answer01.txt
copy input02.txt input.txt
solution
copy output.txt answer02.txt
copy input03.txt input.txt
solution
copy output.txt answer03.txt
copy input04.txt input.txt
solution
copy output.txt answer04.txt
copy input05.txt input.txt
solution
copy output.txt answer05.txt
copy input06.txt input.txt
solution
copy output.txt answer06.txt
copy input07.txt input.txt
solution
copy output.txt answer07.txt
copy input08.txt input.txt
solution
copy output.txt answer08.txt
copy input09.txt input.txt
solution
copy output.txt answer09.txt
copy input10.txt input.txt
solution
copy output.txt answer10.txt
copy input11.txt input.txt
solution
copy output.txt answer11.txt
copy input12.txt input.txt
solution
copy output.txt answer12.txt
copy input13.txt input.txt
solution
copy output.txt answer13.txt
copy input14.txt input.txt
solution
copy output.txt answer14.txt
copy input15.txt input.txt
solution
copy output.txt answer15.txt
copy input16.txt input.txt
solution
copy output.txt answer16.txt
copy input17.txt input.txt
solution
copy output.txt answer17.txt
copy input18.txt input.txt
solution
copy output.txt answer18.txt
copy input19.txt input.txt
solution
copy output.txt answer19.txt
copy input20.txt input.txt
solution
copy output.txt answer20.txt
copy input21.txt input.txt
solution
copy output.txt answer21.txt
copy input22.txt input.txt
solution
copy output.txt answer22.txt
copy input23.txt input.txt
solution
copy output.txt answer23.txt
copy input24.txt input.txt
solution
copy output.txt answer24.txt
copy input25.txt input.txt
solution
copy output.txt answer25.txt
copy input26.txt input.txt
solution
copy output.txt answer26.txt
copy input27.txt input.txt
solution
copy output.txt answer27.txt
copy input28.txt input.txt
solution
copy output.txt answer28.txt
copy input29.txt input.txt
solution
copy output.txt answer29.txt
copy input30.txt input.txt
solution
copy output.txt answer30.txt
copy input31.txt input.txt
solution
copy output.txt answer31.txt
copy input32.txt input.txt
solution
copy output.txt answer32.txt
copy input33.txt input.txt
solution
copy output.txt answer33.txt
copy input34.txt input.txt
solution
copy output.txt answer34.txt
copy input35.txt input.txt
solution
copy output.txt answer35.txt
copy input36.txt input.txt
solution
copy output.txt answer36.txt
copy input37.txt input.txt
solution
copy output.txt answer37.txt
copy input38.txt input.txt
solution
copy output.txt answer38.txt
copy input39.txt input.txt
solution
copy output.txt answer39.txt
copy input40.txt input.txt
solution
copy output.txt answer40.txt
copy input41.txt input.txt
solution
copy output.txt answer41.txt
copy input42.txt input.txt
solution
copy output.txt answer42.txt
copy input43.txt input.txt
solution
copy output.txt answer43.txt
copy input44.txt input.txt
solution
copy output.txt answer44.txt
copy input45.txt input.txt
solution
copy output.txt answer45.txt
copy input46.txt input.txt
solution
copy output.txt answer46.txt
copy input47.txt input.txt
solution
copy output.txt answer47.txt
copy input48.txt input.txt
solution
copy output.txt answer48.txt
copy input49.txt input.txt
solution
copy output.txt answer49.txt
copy input50.txt input.txt
solution
copy output.txt answer50.txt
